language: node_js
node_js:
- node
script:
- npm install
- npm test
deploy:
  app: developer-pub-quiz
  provider: heroku
  api_key:
    secure: hwQJUZE0rdRCnMwvB71UtIz7qBRZ2/u8WZYu4ru5sKe/x8r8pxGwF+yYkbXjKgaDvnzNpjNgrJ1w+eXOLR9PMu0QqbYNxIjyTdyeFQExz/NnGD2byFn3uBQAXTLhyJMoqefANXJHHhaOgOsliH6URAyMSAqqpH9bnUL1MlrTbbS3dYg9DAxcs6jMe6xhCfEV/ginHlcEbXcqDVlUmoIpDTw+cn9fLuT62i+HnI/ItvtIwCqMt9XmNnnKIEcpOhlK2HsJ0AmaAa/n9uUhhahI05JdT4LfLWGPMM/5duSQOiMuHwHccfoqwCac7/y+ipKEC7eqimvi1JkKBx69y/rnp5MaK86tMNL58fK8bGZvVf57SSLhVdhnY5Ow9S94Rta1JUf5a3pEr6bEUuXb/M89Lh0pfy7CKKx/lWpwNAzluxfQj2SfGaS1vvVoUizXwe0swMxUSn5PfXWxb7W19N+N7ZLxIpBhvS/WTxwFJaCPRH9XAKMAxWyDcesBobbMUX6TFFQyWy0RhLRagHts14z/OT6Wb0vqdNm4B2p1jplWPxFU+3Gf3teNkoSU/RxyqknClfupvQkriWYTwNuVgX7S4J7xIe5A1iX4+PESDECUHF4xcCcVFCgYPfnfWz/GmFl8DPe8ROBLV9isU3dI9v0n0oqPLbZDk196VhiHfAWFVGg=
