language: node_js
node_js:
- node
script:
- npm install
- npm test
deploy:
  app: developer-pub-quiz
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: Jgqf3tqzqMg5k2o7aTqNeZWuDN3SeFGHVlOo+55IntcDVnZCV8dq3JIfC2xGj/TAF+2eBWl+y1Kj6lsYivY7J9g8bbCkk9QrRfsVvlNbU/BAya+Yd4fjIfAJL5bXCcVLvJEQG0pIF4qAIQ+nREhhPwVX8pqAYCnPJjSbJmpOX9IN5q3qhBtZ0kgulvaeWQ1633JLuCs1SatBOL3QhmyJsXoBnEissedAFamOuyWbhAHkw0yyt0YjDuNgEWHaMiOocsSHqEQTXEO7CTbPMyVMQ1bVDcBrPW74qvjbxDxY3mJrT3UOUDg8OeXX0u9vmL5PhlmxtMVEi80ywQPb7+9TFFvyscqQOJkdbD2TTxNufNi43lGf0OwNPjbD9xfNe7bJLPwEgQ4pGNItVThZF4n9u2cDBlXrqRbaxCaPJg8TfY2/uy/CoPO7VgRtKnwkr7bJESXBErvVuf50MvA/FK5Lna0FRY/wqToNLXjrrxyni5nfot/i2YkDOLFJ6VH2ZFup6GW8ijrYUD9IHUTSWdTb1o6MbFQ84cNdpxoMVWQd0PjSR1ZFfCzalJEFReDYr2UtZMdtVr5ycDqgx9iObrvzjIMAEgSGaGZwfACk8Vy7o3fMkhgQY76FqXUt5vi5KHD4mLOUsw2hcMV2VWx5BAVs/cnwUkANNKD37qUp7iSNTOc=
